### ISSUE TITLE
Project Plan Requirements

### ISSUE THREAD

**Issue by t4sk** [Mysolarikk/paystack#1]
Hi @jibolaoseni, sorry for the misunderstanding but we don't need any of this.

![Screenshot from 2019-09-18 09-40-02](https://user-images.githubusercontent.com/8084705/65094554-56081d80-d9f8-11e9-9f8e-30e48b507b35.png)

Here is what we need.

**Account (if possible)**
- [ ] if possible setup an demo account to test out Paystack API

**Code**
- [ ] script (node js preferred) demonstrating how to fetch  account balance from Paystack API, and `console.log` the response.
- [ ] script (node js preferred) demonstrating how to fetch transactions for the demo account from Paystack API, and `console.log` the response.

**Documentation**
- [ ] Please document any issues that you know which is not mentioned on the [official API page](
https://developers.paystack.co/)

**Comment by jibolaoseni** [comment]
1. Account has been created.
2. Fetching transactions and account balance from Paystack API endpoints will be created.

**Comment by jibolaoseni** [comment]
- Sample payment link, test cards can be used to complete transaction.
   https://paystack.com/pay/liquidstar

- Transaction records are in Paystack dashboard for the test account
- With provided API/Webhook
-  Configure events listener on the webhook to the callback url 
- Post response from transactions history to dashboard.

`{
  "event": "charge.success",
  "data": {
    "id": 84,
    "domain": "test",
    "status": "success",
    "reference": "9cfbae6e-bbf3-5b41-8aef-d72c1a17650g",
    "amount": 50000,
    "message": null,
    "gateway_response": "Approved",
    "paid_at": "2018-12-20T15:00:06.000Z",
    "created_at": "2018-12-20T15:00:05.000Z",
    "channel": "card",
    "currency": "NGN",
    "ip_address": null,
    "metadata": {
      "custome_fields": [
        {
          "display_name": "customField",
          "variable_name": "customField",
          "Phone": "custom field"
        }
      ]
    },`
=================================================================
Account Balance
=================================================================

![image](https://user-images.githubusercontent.com/1547088/65142661-1bf44700-da0b-11e9-9b2f-6fe6369599a6.png)

![image](https://user-images.githubusercontent.com/1547088/65142726-447c4100-da0b-11e9-8806-de11e5541539.png)

**Comment by lpninja** [comment]
Well done @jibolaoseni. Is this the output of the script you made? Can you also send us an example of the script?

**Comment by jibolaoseni** [comment]
![image](https://user-images.githubusercontent.com/1547088/65307979-f8530d00-db80-11e9-8fd0-991a8eb6463a.png)

**Comment by jibolaoseni** [comment]
{
  "status": true,
  "message": "Transactions retrieved",
  "data": [
    {
      "id": 269372349,
      "domain": "test",
      "status": "success",
      "reference": "T166866577331096",
      "amount": 100000,
      "message": null,
      "gateway_response": "Successful",
      "paid_at": "2019-09-19T00:24:13.000Z",
      "created_at": "2019-09-19T00:23:58.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "153.213.65.23",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": {
        "start_time": 1568852639,
        "time_spent": 14,
        "attempts": 1,
        "errors": 0,
        "success": true,
        "mobile": false,
        "input": [],
        "history": [
          {
            "type": "action",
            "message": "Set payment method to: bank",
            "time": 2
          },
          {
            "type": "action",
            "message": "Set payment method to: card",
            "time": 8
          },
          {
            "type": "action",
            "message": "Attempted to pay with card",
            "time": 13
          },
          {
            "type": "success",
            "message": "Successfully paid with card",
            "time": 14
          }
        ]
      },
      "fees": 1500,
      "fees_split": null,
      "customer": {
        "id": 12705633,
        "first_name": null,
        "last_name": null,
        "email": "lp@solcrypto.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_wgqus64ba8bizu5",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": "AUTH_m2dxp1bdyf",
        "bin": "408408",
        "last4": "4081",
        "exp_month": "12",
        "exp_year": "2020",
        "channel": "card",
        "card_type": "visa DEBIT",
        "bank": "Test Bank",
        "country_code": "NG",
        "brand": "visa",
        "reusable": true,
        "signature": "SIG_iYbpqbsNQtA8WXEUYr37"
      },
      "plan": {},
      "subaccount": {},
      "order_id": 11696,
      "paidAt": "2019-09-19T00:24:13.000Z",
      "createdAt": "2019-09-19T00:23:58.000Z"
    },
    {
      "id": 269372335,
      "domain": "test",
      "status": "abandoned",
      "reference": "T790597038947838",
      "amount": 100000,
      "message": null,
      "gateway_response": "The transaction was not completed",
      "paid_at": null,
      "created_at": "2019-09-19T00:23:56.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "153.213.65.23",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": null,
      "fees": null,
      "fees_split": null,
      "customer": {
        "id": 12705633,
        "first_name": null,
        "last_name": null,
        "email": "lp@solcrypto.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_wgqus64ba8bizu5",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": null,
        "bin": null,
        "last4": null,
        "exp_month": null,
        "exp_year": null,
        "channel": null,
        "card_type": null,
        "bank": null,
        "country_code": null,
        "brand": null,
        "reusable": false,
        "signature": null
      },
      "plan": {},
      "subaccount": {},
      "order_id": null,
      "paidAt": null,
      "createdAt": "2019-09-19T00:23:56.000Z"
    },
    {
      "id": 269371292,
      "domain": "test",
      "status": "success",
      "reference": "T631834556024490",
      "amount": 100000,
      "message": null,
      "gateway_response": "Successful",
      "paid_at": "2019-09-19T00:20:31.000Z",
      "created_at": "2019-09-19T00:19:54.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "153.213.65.23",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": {
        "start_time": 1568852395,
        "time_spent": 37,
        "attempts": 1,
        "errors": 0,
        "success": true,
        "mobile": false,
        "input": [],
        "history": [
          {
            "type": "action",
            "message": "Set payment method to: bank",
            "time": 8
          },
          {
            "type": "action",
            "message": "Set payment method to: card",
            "time": 11
          },
          {
            "type": "action",
            "message": "Attempted to pay with card",
            "time": 35
          },
          {
            "type": "success",
            "message": "Successfully paid with card",
            "time": 37
          }
        ]
      },
      "fees": 1500,
      "fees_split": null,
      "customer": {
        "id": 12705633,
        "first_name": null,
        "last_name": null,
        "email": "lp@solcrypto.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_wgqus64ba8bizu5",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": "AUTH_r1xx55fdoj",
        "bin": "408408",
        "last4": "4081",
        "exp_month": "12",
        "exp_year": "2020",
        "channel": "card",
        "card_type": "visa DEBIT",
        "bank": "Test Bank",
        "country_code": "NG",
        "brand": "visa",
        "reusable": true,
        "signature": "SIG_iYbpqbsNQtA8WXEUYr37"
      },
      "plan": {},
      "subaccount": {},
      "order_id": 11695,
      "paidAt": "2019-09-19T00:20:31.000Z",
      "createdAt": "2019-09-19T00:19:54.000Z"
    },
    {
      "id": 268709941,
      "domain": "test",
      "status": "success",
      "reference": "T793244022780613",
      "amount": 500000,
      "message": "madePayment",
      "gateway_response": "Approved",
      "paid_at": "2019-09-18T10:27:36.000Z",
      "created_at": "2019-09-18T10:26:56.000Z",
      "channel": "bank",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": {
        "start_time": 1568802416,
        "time_spent": 41,
        "attempts": 1,
        "authentication": "payment_token",
        "errors": 0,
        "success": true,
        "mobile": false,
        "input": [],
        "history": [
          {
            "type": "action",
            "message": "Set payment method to: bank",
            "time": 2
          },
          {
            "type": "input",
            "message": "Filled this field: account number",
            "time": 5
          },
          {
            "type": "action",
            "message": "Attempted to pay with bank account",
            "time": 5
          },
          {
            "type": "auth",
            "message": "Authentication Required: birthday",
            "time": 5
          },
          {
            "type": "auth",
            "message": "Authentication Required: registration_token",
            "time": 19
          },
          {
            "type": "auth",
            "message": "Authentication Required: payment_token",
            "time": 32
          },
          {
            "type": "success",
            "message": "Successfully paid with bank account",
            "time": 41
          }
        ]
      },
      "fees": 17500,
      "fees_split": null,
      "customer": {
        "id": 12668068,
        "first_name": null,
        "last_name": null,
        "email": "jibolaoseni@gmail.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_iu5sn5fsz4wn54n",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": "AUTH_lvgpix92sm",
        "bin": "000XXX",
        "last4": "X000",
        "exp_month": "12",
        "exp_year": "9999",
        "channel": "bank",
        "card_type": "",
        "bank": "Zenith Bank",
        "country_code": "NG",
        "brand": "Zenith Emandate",
        "reusable": false,
        "signature": null
      },
      "plan": {},
      "subaccount": {},
      "order_id": 10515,
      "paidAt": "2019-09-18T10:27:36.000Z",
      "createdAt": "2019-09-18T10:26:56.000Z"
    },
    {
      "id": 268709935,
      "domain": "test",
      "status": "abandoned",
      "reference": "T557945523279936",
      "amount": 500000,
      "message": null,
      "gateway_response": "The transaction was not completed",
      "paid_at": null,
      "created_at": "2019-09-18T10:26:55.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": null,
      "fees": null,
      "fees_split": null,
      "customer": {
        "id": 12668068,
        "first_name": null,
        "last_name": null,
        "email": "jibolaoseni@gmail.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_iu5sn5fsz4wn54n",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": null,
        "bin": null,
        "last4": null,
        "exp_month": null,
        "exp_year": null,
        "channel": null,
        "card_type": null,
        "bank": null,
        "country_code": null,
        "brand": null,
        "reusable": false,
        "signature": null
      },
      "plan": {},
      "subaccount": {},
      "order_id": null,
      "paidAt": null,
      "createdAt": "2019-09-18T10:26:55.000Z"
    },
    {
      "id": 268709726,
      "domain": "test",
      "status": "success",
      "reference": "T794423664463663",
      "amount": 2100000,
      "message": null,
      "gateway_response": "Successful",
      "paid_at": "2019-09-18T10:26:40.000Z",
      "created_at": "2019-09-18T10:26:33.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": {
        "start_time": 1568802393,
        "time_spent": 7,
        "attempts": 1,
        "errors": 0,
        "success": true,
        "mobile": false,
        "input": [],
        "history": [
          {
            "type": "action",
            "message": "Attempted to pay with card",
            "time": 6
          },
          {
            "type": "success",
            "message": "Successfully paid with card",
            "time": 7
          }
        ]
      },
      "fees": 41500,
      "fees_split": null,
      "customer": {
        "id": 12668068,
        "first_name": null,
        "last_name": null,
        "email": "jibolaoseni@gmail.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_iu5sn5fsz4wn54n",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": "AUTH_n5b6e4vm7x",
        "bin": "408408",
        "last4": "4081",
        "exp_month": "12",
        "exp_year": "2020",
        "channel": "card",
        "card_type": "visa DEBIT",
        "bank": "Test Bank",
        "country_code": "NG",
        "brand": "visa",
        "reusable": true,
        "signature": "SIG_iYbpqbsNQtA8WXEUYr37"
      },
      "plan": {},
      "subaccount": {},
      "order_id": 10513,
      "paidAt": "2019-09-18T10:26:40.000Z",
      "createdAt": "2019-09-18T10:26:33.000Z"
    },
    {
      "id": 268709723,
      "domain": "test",
      "status": "abandoned",
      "reference": "T637331119463057",
      "amount": 2100000,
      "message": null,
      "gateway_response": "The transaction was not completed",
      "paid_at": null,
      "created_at": "2019-09-18T10:26:33.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": null,
      "fees": null,
      "fees_split": null,
      "customer": {
        "id": 12668068,
        "first_name": null,
        "last_name": null,
        "email": "jibolaoseni@gmail.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_iu5sn5fsz4wn54n",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": null,
        "bin": null,
        "last4": null,
        "exp_month": null,
        "exp_year": null,
        "channel": null,
        "card_type": null,
        "bank": null,
        "country_code": null,
        "brand": null,
        "reusable": false,
        "signature": null
      },
      "plan": {},
      "subaccount": {},
      "order_id": null,
      "paidAt": null,
      "createdAt": "2019-09-18T10:26:33.000Z"
    },
    {
      "id": 268709350,
      "domain": "test",
      "status": "success",
      "reference": "T092996094067012",
      "amount": 500000,
      "message": null,
      "gateway_response": "Successful",
      "paid_at": "2019-09-18T10:26:06.000Z",
      "created_at": "2019-09-18T10:25:50.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": {
        "start_time": 1568802350,
        "time_spent": 17,
        "attempts": 2,
        "errors": 1,
        "success": true,
        "mobile": false,
        "input": [],
        "history": [
          {
            "type": "action",
            "message": "Attempted to pay with card",
            "time": 6
          },
          {
            "type": "error",
            "message": "Error: Declined",
            "time": 6
          },
          {
            "type": "action",
            "message": "Attempted to pay with card",
            "time": 16
          },
          {
            "type": "success",
            "message": "Successfully paid with card",
            "time": 17
          }
        ]
      },
      "fees": 17500,
      "fees_split": null,
      "customer": {
        "id": 12668933,
        "first_name": null,
        "last_name": null,
        "email": "dele@alli.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_9dimjcfkdbk4uel",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": "AUTH_esr9c6h1n3",
        "bin": "408408",
        "last4": "4081",
        "exp_month": "12",
        "exp_year": "2020",
        "channel": "card",
        "card_type": "visa DEBIT",
        "bank": "Test Bank",
        "country_code": "NG",
        "brand": "visa",
        "reusable": true,
        "signature": "SIG_iYbpqbsNQtA8WXEUYr37"
      },
      "plan": {},
      "subaccount": {},
      "order_id": 10509,
      "paidAt": "2019-09-18T10:26:06.000Z",
      "createdAt": "2019-09-18T10:25:50.000Z"
    },
    {
      "id": 268709340,
      "domain": "test",
      "status": "abandoned",
      "reference": "T338727334377064",
      "amount": 500000,
      "message": null,
      "gateway_response": "The transaction was not completed",
      "paid_at": null,
      "created_at": "2019-09-18T10:25:49.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": null,
      "fees": null,
      "fees_split": null,
      "customer": {
        "id": 12668933,
        "first_name": null,
        "last_name": null,
        "email": "dele@alli.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_9dimjcfkdbk4uel",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": null,
        "bin": null,
        "last4": null,
        "exp_month": null,
        "exp_year": null,
        "channel": null,
        "card_type": null,
        "bank": null,
        "country_code": null,
        "brand": null,
        "reusable": false,
        "signature": null
      },
      "plan": {},
      "subaccount": {},
      "order_id": null,
      "paidAt": null,
      "createdAt": "2019-09-18T10:25:49.000Z"
    },
    {
      "id": 268707572,
      "domain": "test",
      "status": "success",
      "reference": "T887697461515764",
      "amount": 500000,
      "message": "test-3ds",
      "gateway_response": "[Test] Approved",
      "paid_at": "2019-09-18T10:22:46.000Z",
      "created_at": "2019-09-18T10:22:24.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": {
        "start_time": 1568802145,
        "time_spent": 22,
        "attempts": 2,
        "authentication": "3DS",
        "errors": 1,
        "success": true,
        "mobile": false,
        "input": [],
        "history": [
          {
            "type": "action",
            "message": "Attempted to pay with card",
            "time": 5
          },
          {
            "type": "error",
            "message": "Error: Declined",
            "time": 6
          },
          {
            "type": "action",
            "message": "Attempted to pay with card",
            "time": 17
          },
          {
            "type": "auth",
            "message": "Authentication Required: 3DS",
            "time": 17
          },
          {
            "type": "action",
            "message": "Third-party authentication window opened",
            "time": 21
          },
          {
            "type": "success",
            "message": "Successfully paid with card",
            "time": 22
          }
        ]
      },
      "fees": 17500,
      "fees_split": null,
      "customer": {
        "id": 12668068,
        "first_name": null,
        "last_name": null,
        "email": "jibolaoseni@gmail.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_iu5sn5fsz4wn54n",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": "AUTH_cpy4ovxkz5",
        "bin": "408408",
        "last4": "0409",
        "exp_month": "12",
        "exp_year": "2020",
        "channel": "card",
        "card_type": "visa DEBIT",
        "bank": "Test Bank",
        "country_code": "NG",
        "brand": "visa",
        "reusable": true,
        "signature": "SIG_l3WlCVDRDmokExl3ugCq"
      },
      "plan": {},
      "subaccount": {},
      "order_id": 10499,
      "paidAt": "2019-09-18T10:22:46.000Z",
      "createdAt": "2019-09-18T10:22:24.000Z"
    },
    {
      "id": 268707562,
      "domain": "test",
      "status": "abandoned",
      "reference": "T648777356924544",
      "amount": 500000,
      "message": null,
      "gateway_response": "The transaction was not completed",
      "paid_at": null,
      "created_at": "2019-09-18T10:22:23.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": null,
      "fees": null,
      "fees_split": null,
      "customer": {
        "id": 12668068,
        "first_name": null,
        "last_name": null,
        "email": "jibolaoseni@gmail.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_iu5sn5fsz4wn54n",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": null,
        "bin": null,
        "last4": null,
        "exp_month": null,
        "exp_year": null,
        "channel": null,
        "card_type": null,
        "bank": null,
        "country_code": null,
        "brand": null,
        "reusable": false,
        "signature": null
      },
      "plan": {},
      "subaccount": {},
      "order_id": null,
      "paidAt": null,
      "createdAt": "2019-09-18T10:22:23.000Z"
    },
    {
      "id": 268707158,
      "domain": "test",
      "status": "success",
      "reference": "T620662921247677",
      "amount": 1000000,
      "message": null,
      "gateway_response": "Successful",
      "paid_at": "2019-09-18T10:21:52.000Z",
      "created_at": "2019-09-18T10:21:40.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": {
        "start_time": 1568802101,
        "time_spent": 12,
        "attempts": 1,
        "errors": 0,
        "success": true,
        "mobile": false,
        "input": [],
        "history": [
          {
            "type": "action",
            "message": "Attempted to pay with card",
            "time": 11
          },
          {
            "type": "success",
            "message": "Successfully paid with card",
            "time": 12
          }
        ]
      },
      "fees": 25000,
      "fees_split": null,
      "customer": {
        "id": 12668068,
        "first_name": null,
        "last_name": null,
        "email": "jibolaoseni@gmail.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_iu5sn5fsz4wn54n",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": "AUTH_slqy1rpndt",
        "bin": "408408",
        "last4": "4081",
        "exp_month": "12",
        "exp_year": "2020",
        "channel": "card",
        "card_type": "visa DEBIT",
        "bank": "Test Bank",
        "country_code": "NG",
        "brand": "visa",
        "reusable": true,
        "signature": "SIG_iYbpqbsNQtA8WXEUYr37"
      },
      "plan": {},
      "subaccount": {},
      "order_id": 10496,
      "paidAt": "2019-09-18T10:21:52.000Z",
      "createdAt": "2019-09-18T10:21:40.000Z"
    },
    {
      "id": 268707150,
      "domain": "test",
      "status": "abandoned",
      "reference": "T600798269475323",
      "amount": 1000000,
      "message": null,
      "gateway_response": "The transaction was not completed",
      "paid_at": null,
      "created_at": "2019-09-18T10:21:39.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": null,
      "fees": null,
      "fees_split": null,
      "customer": {
        "id": 12668068,
        "first_name": null,
        "last_name": null,
        "email": "jibolaoseni@gmail.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_iu5sn5fsz4wn54n",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": null,
        "bin": null,
        "last4": null,
        "exp_month": null,
        "exp_year": null,
        "channel": null,
        "card_type": null,
        "bank": null,
        "country_code": null,
        "brand": null,
        "reusable": false,
        "signature": null
      },
      "plan": {},
      "subaccount": {},
      "order_id": null,
      "paidAt": null,
      "createdAt": "2019-09-18T10:21:39.000Z"
    },
    {
      "id": 268706472,
      "domain": "test",
      "status": "success",
      "reference": "T704369561003610",
      "amount": 500000,
      "message": null,
      "gateway_response": "Successful",
      "paid_at": "2019-09-18T10:20:32.000Z",
      "created_at": "2019-09-18T10:20:24.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": {
        "start_time": 1568802024,
        "time_spent": 9,
        "attempts": 1,
        "errors": 0,
        "success": true,
        "mobile": false,
        "input": [],
        "history": [
          {
            "type": "action",
            "message": "Attempted to pay with card",
            "time": 8
          },
          {
            "type": "success",
            "message": "Successfully paid with card",
            "time": 9
          }
        ]
      },
      "fees": 17500,
      "fees_split": null,
      "customer": {
        "id": 12668068,
        "first_name": null,
        "last_name": null,
        "email": "jibolaoseni@gmail.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_iu5sn5fsz4wn54n",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": "AUTH_dfkeiebe2l",
        "bin": "408408",
        "last4": "4081",
        "exp_month": "12",
        "exp_year": "2020",
        "channel": "card",
        "card_type": "visa DEBIT",
        "bank": "Test Bank",
        "country_code": "NG",
        "brand": "visa",
        "reusable": true,
        "signature": "SIG_iYbpqbsNQtA8WXEUYr37"
      },
      "plan": {},
      "subaccount": {},
      "order_id": 10493,
      "paidAt": "2019-09-18T10:20:32.000Z",
      "createdAt": "2019-09-18T10:20:24.000Z"
    },
    {
      "id": 268706465,
      "domain": "test",
      "status": "abandoned",
      "reference": "T117352010236289",
      "amount": 500000,
      "message": null,
      "gateway_response": "The transaction was not completed",
      "paid_at": null,
      "created_at": "2019-09-18T10:20:23.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": null,
      "fees": null,
      "fees_split": null,
      "customer": {
        "id": 12668068,
        "first_name": null,
        "last_name": null,
        "email": "jibolaoseni@gmail.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_iu5sn5fsz4wn54n",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": null,
        "bin": null,
        "last4": null,
        "exp_month": null,
        "exp_year": null,
        "channel": null,
        "card_type": null,
        "bank": null,
        "country_code": null,
        "brand": null,
        "reusable": false,
        "signature": null
      },
      "plan": {},
      "subaccount": {},
      "order_id": null,
      "paidAt": null,
      "createdAt": "2019-09-18T10:20:23.000Z"
    },
    {
      "id": 268701247,
      "domain": "test",
      "status": "success",
      "reference": "T171674606989422",
      "amount": 100000,
      "message": null,
      "gateway_response": "Successful",
      "paid_at": "2019-09-18T10:19:13.000Z",
      "created_at": "2019-09-18T10:10:56.000Z",
      "channel": "card",
      "currency": "NGN",
      "ip_address": "154.113.72.110",
      "metadata": {
        "referrer": "https://paystack.com/pay/liquidstar"
      },
      "log": {
        "start_time": 1568801456,
        "time_spent": 497,
        "attempts": 1,
        "errors": 0,
        "success": true,
        "mobile": false,
        "input": [],
        "history": [
          {
            "type": "action",
            "message": "Set payment method to: bank",
            "time": 6
          },
          {
            "type": "action",
            "message": "Set payment method to: card",
            "time": 451
          },
          {
            "type": "input",
            "message": "Filled this field: card number",
            "time": 454
          },
          {
            "type": "input",
            "message": "Filled this field: card cvv",
            "time": 462
          },
          {
            "type": "input",
            "message": "Filled this field: card expiry",
            "time": 480
          },
          {
            "type": "action",
            "message": "Attempted to pay with card",
            "time": 497
          },
          {
            "type": "success",
            "message": "Successfully paid with card",
            "time": 497
          }
        ]
      },
      "fees": 1500,
      "fees_split": null,
      "customer": {
        "id": 12668068,
        "first_name": null,
        "last_name": null,
        "email": "jibolaoseni@gmail.com",
        "phone": null,
        "metadata": null,
        "customer_code": "CUS_iu5sn5fsz4wn54n",
        "risk_action": "default"
      },
      "authorization": {
        "authorization_code": "AUTH_or0e8df24s",
        "bin": "408408",
        "last4": "4081",
        "exp_month": "12",
        "exp_year": "2020",
        "channel": "card",
        "card_type": "visa DEBIT",
        "bank": "Test Bank",
        "country_code": "NG",
        "brand": "visa",
        "reusable": true,
        "signature": "SIG_iYbpqbsNQtA8WXEUYr37"
      },
      "plan": {},
      "subaccount": {},
      "order_id": 10463,
      "paidAt": "2019-09-18T10:19:13.000Z",
      "createdAt": "2019-09-18T10:10:56.000Z"
    }
  ],
  "meta": {
    "total": 16,
    "total_volume": 106000,
    "skipped": 0,
    "perPage": 50,
    "page": 1,
    "pageCount": 1
  }
}

**Comment by lpninja** [comment]
Hi @jibolaoseni --that's really great. Can you show us the actual code to get that above JSON response?

**Comment by jibolaoseni** [comment]
Links to videos of Paystack API testing. 
https://drive.google.com/file/d/1ka03ctkGXWNuopgIYan3TZ5smODxdYX0/view?usp=sharing

https://drive.google.com/file/d/12VnEuzTB1LxqOMkA-S9A6CXNNpII67Y_/view?usp=sharing

===============================================================

**Comment by jibolaoseni** [comment]
No code has been written, just testing the API endpoints, parameters and fetching data from accounts.

**Comment by t4sk** [comment]
@jibolaoseni Thanks for the video. It helps us visualize how to integrate paystack into our server.

Can you write the code to  fetch data? You can  put a placeholder for sensitive credentials. For example

```node
const API_SECRET = "my secret"

coonst PAYSTACK_URL = "...."

fetch({
  url: PAYSTACK_URL,
  // other params like API secret...
}, (error, response) => {
  console.log(response)
})
```

**Comment by lpninja** [comment]
Thanks for the video @jibolaoseni. We will have a call with Scott today or tomorrow to go over it as well. Thanks for the example @t4sk

**Comment by jibolaoseni** [comment]
Have you been able to run the code locally.

**Comment by t4sk** [comment]
@jibolaoseni Thanks I ran the code on `Fetch` branch. It works, great!

How is `customer_code` retrieved? Would we be able to get it using API calls, if we know the 
customer's id?

```
    fetch(
      "https://api.paystack.co/transaction/?id=380380&customer_code=CUS_wgqus64ba8bizu5",
      {
```

Thanks

**Comment by jibolaoseni** [comment]
@t4sk The example script for fetching the account balance is the branch Paystack API GET. Can you make this a private repo?
